### ISSUE TITLE
Where is verification code?

### ISSUE THREAD

**Issue by master-q** [echronos/echronos#13]
In example of seL4, the verification code is found at https://github.com/seL4/l4v. Where is verification code of eChronos RTOS?

**Comment by lsf37** [comment]
The specs and proofs for eChronos are not public at this stage.

Note that at this stage eChronos has only fully undergone code-level verification by model-checking to exclude undefined C behaviour. The full functional correctness verification in Isabelle/HOL is still in progress.

**Comment by master-q** [comment]
> The specs and proofs for eChronos are not public at this stage.

I understand it. Thanks.
