### ISSUE TITLE
Fix hard-coded interrupt priority resolution

### ISSUE THREAD

**Issue by Schnommus** [echronos/echronos#16]
(symptom: hard-reset during context switch on pre-emptive OS variants only)

**Problem:**
* At the moment, the interrupt priority of PendSV & SVC are fixed (at 4 bits max), however different hardware variants will likely change this.
* For example, the TI microcontroller I am using only has 3 bits of interrupt priority resolution.
* As soon as less priority resolution is available than is used in eChronos' implementation, BASEPRI sits on top of both of these interrupts (during a context switch) meaning neither can be called; and the system hard-resets.
* The relevant pieces of code are in the pre-emptive context-switching implementations, for example components/context-switch-preempt-armv7m:98:
```c
#define SVCALL_PRIORITY 224u
#define PENDSV_PRIORITY 240u
```
* And also in the assembly code used for pre-emptive context switching, for example packages/armv7/ctxt-switch-preempt.s:72:
```asm
/* Setting BASEPRI to the same priority value as that of a configurable-priority interrupt disables the interrupt. */
.macro asm_preempt_disable scratch
        /* This hardcoded value must match the PendSV priority set by the ARM-specific preempt_init. */
        ldr \scratch, =#240
        msr basepri, \scratch
.endm
```
**Possible fix**
* Add these parameters to the templates. Perhaps it would be nicest to have a 'priority_resolution_bits' schema tag, which automatically (from n bits) computes `2^n<<(8-n)` and `(2^n-1)<<(8-n)` as priority levels for PendSV and SVC to avoid someone having to figure these values out correctly.

**Comment by stefangotz** [comment]
Resolved by task branch rs2aHG-fix_hardcoded_interrupt_priority_resolution integrated with revision 7b2f0fa9e1db452d4ad575eae8a758bca89c9516. Thanks Seb!
