### ISSUE TITLE
Fix message queue 'type' parameter

### ISSUE THREAD

**Issue by Schnommus** [echronos/echronos#17]
* I came across this whilst trying to port message queues across from Rigel to Kochab. I'm pretty sure this is a bug in Rigel.
* Take a look at this: (from components/message-queue/implementation.c:34)
```c
{{#message_queues.length}}
{{#message_queues}}
static uint8_t message_queue_{{name}}_messages[{{queue_length}}][{{message_size}}];
{{/message_queues}}
static struct message_queue message_queues[] =
{
{{#message_queues}}
    {
        (uint8_t*)message_queue_{{name}}_messages,
{{#message_size}}
        {{message_size}},
{{/message_size}}
{{#message_type}}
        sizeof({{message_type}}),
{{/message_type}}
```
* So in the above, line 36 you can see that `{{message_size}}` is used to provide the second dimension of `message_queue_x_messages`
* However, in the documentation it is listed: (and you can also see from line 47):

> **message_queues/message_queue/message_type**
This configuration item specifies the C type of each message in the queue from which the size of the messages is derived. This is an optional configuration item with no default. Either message_size or message_type needs to be specified for a message queue.

* With the above implementation, the absence of message_size results in python replacing it with 'None', hence a compiler error.
* This means that you can't use message_type.

**Comment by stefangotz** [comment]
Resolved by task branch a4Pub3-fix_message_queue_type_parameter integrated with revision 86c991c21d5dda70e27474473c5f1b6c05dcd4a9
