### ISSUE TITLE
Assign ARM bitband data to separate data segment

### ISSUE THREAD

**Issue by stefangotz** [echronos/echronos#22]
# Motivation

On ARM, the file vectable.s is set up such that regular data and bitband data reside in the same linker data segment.
This can lead to a misalignment of either the bitband or the regular data after loading it into RAM due to differences between VMA and LMA addresses.
To solve this issue, it is sufficient to place the bitband and regular data into separate linker data segments.
# Goals

Modify the file vectable.s so that bitband and regular data resides in separate linker data segments.
# Test Plan

**Comment by schnommus** [comment]
Fixed in sqwilI-armv7m_linker_script_refinement (6eff409cc6cc8e2de848e7c6a56beda55be36b1b), albeit with forced alignments rather than section separation.
