### ISSUE TITLE
Differences Between Phact and Kochab Variants for PPC e500

### ISSUE THREAD

**Issue by johnkrainski** [echronos/echronos#3]
Can you provide a brief summary of the differences between the Phact and Kochab variants of eChronos for the PPC e500 platform?

Thanks,
John

**Comment by ikuz** [comment]
The key difference is that Kochab provides priority inheritance while Phact provides priority ceiling.

**Comment by stefangotz** [comment]
@johnkrainski I'll close this issue assuming this answered your question? Thanks for your input, btw, we will work on making this sort of information more accessible.

**Comment by johnkrainski** [comment]
Yes, thank you!
