### ISSUE TITLE
Potential linker script issue on armv7m

### ISSUE THREAD

**Issue by schnommus** [echronos/echronos#41]
# Motivation

- I came across an issue whilst porting eChronos to TI's TM4C123GXL development board recently.
- Essentially the linker script was using a misaligned PhysAddr, which resulted in any accesses to data in the .rodata section being misaligned. From readelf:
```
Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x010000 0x00000000 0x00000000 0x06146 0x06146 R E 0x10000
  LOAD           0x016148 0x00006148 0x00006146 0x006cf 0x006cf R   0x10000
  LOAD           0x020000 0x20000000 0x00006818 0x00018 0x0183c RW  0x10000
```
- One can see that the PhysAddr for the header containing the .rodata section (second LOAD) is 0x..6146 which is misaligned and doesn't match the VirtAddr. This has to match otherwise bad things happen, I was getting all sorts of strange behaviour.

- I then tried forcing the alignment & address match by changing `packages/armv7m/default.ld`:
```
41c39,43
<         .rodata : AT (LOADADDR (.text) + SIZEOF(.text))
---
>         . = LOADADDR (.text) + SIZEOF(.text);
>         . = ALIGN(4);
>         ro_data_start = .;
> 
>         .rodata : AT (ro_data_start)
```
- And that fixed all my issues.
- I think this is due to the .text section size not being 4-byte aligned; a case which we may we may have missed by only having tested 4-byte aligned .text section sizes by coincidence.
- Also I will note that I was using eChronos in a shared-library configuration (linking my main codebase against an echronos shared library) with no third-party bit-band variables, using eChronos' default linker script to generate the elf.
- I'm going to investigate to see if I can create a small reproducible testcase, will update this issue in the near future.

# Goals

- Investigate the cause of this issue
- Construct a small reproducable test-case that only has an echronos dependency
- Create a task to fix the linker script (if this is in fact an issue with eChronos).
- Add the test-case to CI

**Comment by stefangotz** [comment]
Resolved by branch `sqwilI-armv7m_linker_script_refinement` (https://github.com/echronos/echronos/tree/archive/sqwilI-armv7m_linker_script_refinement)
