### ISSUE TITLE
make the Quick Start more accessible

### ISSUE THREAD

**Issue by stefangotz** [echronos/echronos#5]
# Motivation

The Quick Start section in the README.md file is currently relatively complex and depends on a number of non-trivial prerequisites. This makes in unnecessarily difficult to try out and get a feeling for the eChronos RTOS.
# Goals
- base the quick start instructions on a platform with fewer dependencies, such as the systems for the posix or x86 targets
# Test Plan
- test documented quick start instructions to ensure that they are reproducible

**Comment by schnommus** [comment]
Fixed in v1.3.10, task: simplify_getting_started_guide. (3efab6c59142bdc5d6cb2ae0a836ebc4bbc3f8dc)
