### ISSUE TITLE
Pass pylint 2.2 checks

### ISSUE THREAD

**Issue by stefangotz** [echronos/echronos#59]
# Motivation

Currently, the code style tests fail because newer version of pylint report new code style violations that haven't been addressed yet.
This is directly visible in the Travis CI and AppVeyor test results.

# Goals

The goal of this task is to ensure that the code style tests pass again.
To this end, the code base shall be updated such that the most recent version of pylint does not report code style violations.

**Comment by bennoleslie** [comment]
The PR for this has been merged to master (I'm not sure why the issue did not automatically close, I probably did something wrong).
