### ISSUE TITLE
Typo in eChronos Prerequisites

### ISSUE THREAD

**Issue by johnkrainski** [echronos/echronos#8]
I'm pretty sure this:
    git clone git://sourceware.org/git/binutils-gdb.git
should be this:
    git clone https://sourceware.org/git/binutils-gdb.git

**Comment by bennoleslie** [comment]
Cloning via the git protocol works without any problem for me.

It probably also works over https, but I think in general using the git protocol where offered is preferred.

Was there a specific problem you ran into when cloning via the git protocol?

**Comment by johnkrainski** [comment]
Sorry, I'm new to the git protocol.  Turns out it's blocked by my company's firewall.  It also works over https, though, so no worries.  Thanks.
